name: Compilar APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug

      - name: Subir el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: palabra-del-dia-apk
          path: bin/*.apk
